[colors.primary]
background = '#121317'
foreground = '#e2e2e8'

[colors.cursor]
text = '#121317'
cursor = '#e2e2e8'

[colors.vi_mode_cursor]
text = '#121317'
cursor = '#a9c7ff'

[colors.search.matches]
foreground = '#434750'
background = '#f1b1f3'

[colors.search.focused_match]
foreground = '#434750'
background = '#a9c7ff'

[colors.footer_bar]
foreground = '#434750'
background = '#e2e2e8'

[colors.hints.start]
foreground = '#434750'
background = '#b9c7e4'

[colors.hints.end]
foreground = '#434750'
background = '#b9c7e4'

[colors.selection]
text = '#c3c6d1'
background = '#434750'


[colors.normal]
black   = '#434750'
red     = '#ffb4ab'
green   = '#a9c7ff'
yellow  = '#b9c7e4'
blue    = '#f1b1f3'
magenta = '#a9c7ff'
cyan    = '#b9c7e4'
white   = '#e2e2e8'


[colors.bright]
black   = '#8d919b'
red     = '#ffb4ab'
green   = '#a9c7ff'
yellow  = '#b9c7e4'
blue    = '#f1b1f3'
magenta = '#a9c7ff'
cyan    = '#b9c7e4'
white   = '#e2e2e8'


[colors.dim]
black   = '#434750'
red     = '#ffb4ab'
green   = '#a9c7ff'
yellow  = '#b9c7e4'
blue    = '#f1b1f3'
magenta = '#a9c7ff'
cyan    = '#b9c7e4'
white   = '#e2e2e8'
